package com.pechonick.registration.command;

public enum CommandName {
	LOGIN, REGISTRATION, CHANGE_LOCALE, GET_LOGIN_PAGE, GET_REGISTRATION_PAGE, LOGOUT,

    GET_ADMIN_INDEX_INFO, GET_ADMIN_COURSE_INFO, GET_CREATE_COURSE_FORM, GET_EDIT_COURSE_FORM,
    APPOINT_TEACHER_FOR_THE_COURSE, CREATE_COURSE, EDIT_COURSE, START_COURSE, CANCEL_COURSE,
    ADMIN_GET_MORE_COURSES,

    GET_USER_INFO, GET_EDIT_USER_INFO_FORM,

    GET_STUDENT_INDEX_INFO, GET_STUDENT_COURSE_INFO, APPLY_FOR_COURSE, EDIT_STUDENT_INFO, STUDENT_GET_MORE_COURSES,

    GET_TEACHER_INDEX_INFO, GET_TEACHER_COURSE_INFO, EDIT_TEACHER_INFO, GET_ADD_REVIEW_FORM, GET_STUDENT_INFO,
    ADD_STUDENT_REVIEW, TEACHER_GET_MORE_COURSES;

    public String getCommandName() {
        return this.name().replace("_", "-").toLowerCase();
    }
}